### ISSUE TITLE
crossvalidate_fit needs to respect different filter parameters for train and test.

### ISSUE THREAD

**Issue by N-HEDGER** [VU-Cog-Sci/prfpy#12]
Here, you can see that a model takes the 'task_lengths' parameter from the stimulus class and puts it into the filter dictionary for the model. It does this in _init_:

https://github.com/VU-Cog-Sci/prfpy/blob/2bb0e482c065360db72f24e43bea1c15191faaab/prfpy/model.py#L206

Then, in the cross_validate fit method, the stimulus attribute of the model is modified to be the test stimulus:

https://github.com/VU-Cog-Sci/prfpy/blob/2bb0e482c065360db72f24e43bea1c15191faaab/prfpy/fit.py#L309

However, since we only modify the stimulus attribute of the model and don't call its _init_ , the task_lengths for the model will remain unchanged - and will still reflect those of the training stimulus - because the model's filter dictionary is not updated.

This means that when generating the predictions for the test dataset, the predictions will be filtered according to the task lengths of the training stimulus. This can cause havoc if the task lengths/data are different sizes between train and test.

The reason this probably hasn't been noticed before is that you would ordinarily want identical *filter* parameters between train and test. However, the problem is raised because the task lengths are also stored within the filter dictionary - which could quite often vary between train and test.

Any solution would need to respect the fact that the updated filter parameters would again need to be changed back to reflect the training set after the predictions for the test are generated (similar to how the model.stimulus is replaced and then restored in crossvalidate_fit)

**Comment by marcoaqil** [comment]
should be fixed in 
https://github.com/VU-Cog-Sci/prfpy/commit/bea15379d794b2bb4529938d68bd24db4d3a01f2
